### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by cking** [KyleMayes/vulkanalia#15]
`libloading` was released in v0.7
`winit` was released in v0.24 (as an alternative to winit, you could switch to `raw-window-handle` - which is implemented by `winit`, `sdl2` and `glfw` for example)

**Comment by KyleMayes** [comment]
I didn't know about `raw-window-handle`, thanks for the recommendation!
I've switched over to using `raw-window-handle` instead of directly integrating with `winit` since it is more flexible.
That change, dependency updates, and some other improvements noted in the changelog have been released in `v0.4.0`.
