### ISSUE TITLE
Add support for Vulkan video extensions

### ISSUE THREAD

**Issue by LouChiSoft** [KyleMayes/vulkanalia#195]
Hi, I noticed when printing out the queue family data for my GPU that one of the the flags that was listed was `0x20` instead of a named flag which when I looked it up is for the `VK_QUEUE_VIDEO_DECODE_BIT` in the Vulkan spec. I double checked the version used in Vulkania and it seems to not have an entry for the decoding bit or the endcoding bit (although encoding is still considered beta IIRC)

**Comment by KyleMayes** [comment]
I purposefully disabled support for the video extensions because they depend on some [additional Vulkan headers](https://github.com/KhronosGroup/Vulkan-Headers/tree/main/include/vk_video) rather than just the types from `vk.xml` like the rest of the API.

https://github.com/KyleMayes/vulkanalia/blob/fcd4818d445433d23f528398efcb4a16aa82eda0/generator/src/main/kotlin/com/kylemayes/generator/registry/Filter.kt#L30-L45

As I noted in that comment, I think it should be possible to support the Vulkan video extensions by using `bindgen` to generate Rust interfaces from those headers, but I haven't really looked into it since I had no need for the video extensions.

I will try investigating this further to see how practical it would be.

**Comment by LouChiSoft** [comment]
Oh, I didn't realise that they were under different headers. That would make sense it's not included then.

**Comment by KyleMayes** [comment]
I just added support for the Vulkan video extensions.

I started working on an example, but it got pretty complicated pretty quickly and I set it aside.  
I was able to make a Vulkan video session successfully, so the basics seem to be working at least.

**Comment by KyleMayes** [comment]
Vulkan video extension are part of the latest release (`v0.23.0`).
As I previously mentioned, I played around with a potential example showcasing the video extensions, but I wasn't able to finish it.
However, I was able to set up some of the basics successfully using the new video extension support so I think it should be working.
