### ISSUE TITLE
My computer doesn't work well in the swapchain chapter of the tutorial.

### ISSUE THREAD

**Issue by swallowvski** [KyleMayes/vulkanalia#63]
My computer doesn't work well in the swapchain chapter of the tutorial.
I have confirmed that the same problem occurs in [06_swapchain_creation](https://github.com/KyleMayes/vulkanalia/blob/master/tutorial/src/06_swapchain_creation.rs)
## PC environment
ubuntu 20.04
rayzen 2700X
rtx2080ti

## version
Vulkan version 1.2.189
rustc 1.56.0

anyhow = "1"
lazy_static = "1"
log = "0.4"
nalgebra-glm = "0.10"
png = "0.16"
pretty_env_logger = "0.4"
tobj = "2"
vulkanalia = { version = "=0.11.0", features = ["libloading", "window"] }
winit = "0.24"

# Error Message 
There is not much information I can provide. Sorry.
Most of the information in the log was general, and there was only a warnings and errors at the end. 

` WARN  graphics > Failed to check physical device suitability: Failed to get required queue family indeces.`
`Error: Failed to find suitable physical device.`

If you want all the logs, I'll upload them all.

**Comment by swallowvski** [comment]
oh! I can't seem to find the present. And get function seems to be running twice.It seems that it stopped at the　`create_logical_device`.
```
warning: `graphics` (bin "graphics") generated 2 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 1.24s
     Running `target/debug/graphics`
[src/main.rs:396] &properties = [
    QueueFamilyProperties {
        queue_flags: GRAPHICS | COMPUTE | TRANSFER | SPARSE_BINDING,
        queue_count: 16,
        timestamp_valid_bits: 64,
        min_image_transfer_granularity: Extent3D {
            width: 1,
            height: 1,
            depth: 1,
        },
    },
    QueueFamilyProperties {
        queue_flags: TRANSFER | SPARSE_BINDING,
        queue_count: 2,
        timestamp_valid_bits: 64,
        min_image_transfer_granularity: Extent3D {
            width: 1,
            height: 1,
            depth: 1,
        },
    },
    QueueFamilyProperties {
        queue_flags: COMPUTE | TRANSFER | SPARSE_BINDING,
        queue_count: 8,
        timestamp_valid_bits: 64,
        min_image_transfer_granularity: Extent3D {
            width: 1,
            height: 1,
            depth: 1,
        },
    },
]
[src/main.rs:396] &properties = [
    QueueFamilyProperties {
        queue_flags: GRAPHICS | COMPUTE | TRANSFER,
        queue_count: 1,
        timestamp_valid_bits: 64,
        min_image_transfer_granularity: Extent3D {
            width: 1,
            height: 1,
            depth: 1,
        },
    },
]
 WARN  graphics > Failed to check physical device suitability: Failed to get required queue family indeces.(graphics=Some(QueueFamilyProperties { queue_flags: GRAPHICS | COMPUTE | TRANSFER, queue_count: 1, timestamp_valid_bits: 64, min_image_transfer_granularity: Extent3D { width: 1, height: 1, depth: 1 } }), present=None).
Error: Failed to find suitable physical device.
```

**Comment by KyleMayes** [comment]
Issue should be completely fixed now!

Turns out the swapchain extension *was* being reported as available by Vulkan, but due to a bug in the way `vulkanalia` was comparing extension names it wasn't being found in the list of available extensions.

The particular fix is this: https://github.com/KyleMayes/vulkanalia/pull/65/commits/30aee5b7bac71f8b868e8435aeb7a17e744b773a#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR15

Extension names are stored in `StringArray`s which are wrappers around an array of `c_char`s. These arrays are supposed to contain null-terminated strings but `vulkanalia` was comparing *all* of the characters in the arrays when checking `StringArray`s for equality so for example `StringArray`s containing `b"VK_KHR_swapchain\0"` and `b"VK_KHR_swapchain\0asdf"` would not be equal even though they are equivalent when interpreted as null-terminated strings.

Sometimes the swapchain extension name reported by Vulkan would have a non-zero character at the end of the array which would result in it not being equal to `vk::KHR_SWAPCHAIN_EXTENSION.name` which has all zeros after the name of the extension.
