### ISSUE TITLE
vkGetBufferDeviceAddress doesn't return anything

### ISSUE THREAD

**Issue by InBetweenNames** [KyleMayes/vulkanalia#81]
https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkGetBufferDeviceAddress.html

This function should return a DeviceAddress, but in Vulkanalia it just returns `()`.  Very simple fix, because the `PFN_` for it is already correct.

**Comment by KyleMayes** [comment]
The code generator was failing to account for Vulkan commands that directly return results instead of using output pointer parameters which impacted not just `vkGetBufferDeviceAddress` but several other commands as well.

This issue, along with another issue related to command wrapper generation, has been fixed in `v0.14.0`.
